### PR TITLE
Tests for MarketContractOraclize and MarketContractFactoryOraclize types

### LINKED ISSUE #8: [MarketContractOraclize] Test converted TypeScript ABI
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story
As a developer, I need to ensure the MARKET API TypeScript ABIs work correctly so that I can correctly interface with the MARKET contracts.

### Why Is this Needed?
*Summary*: We need to have automated test coverage for all TypeScript ABIs. This started as part of https://github.com/MARKETProtocol/MARKET.js/issues/14. Due to the size and scope of the testing, we created a new project and repo for the MARKET.js types.

### Description
*Type*: Enhancement

### Current Behavior
There is minimal test coverage.

### Expected Behavior
We need 100% test coverage on the TypeScript ABIs.

### Solution
*Summary*:
[Typechain](https://github.com/Neufund/TypeChain) is being used to generate types and the ABIs from which to generate the types is specified as a glob pattern in the package.json under config.typechain.include which is currently set to: Market*|CollateralToken|OraclizeQueryTest|ERC20|OrderLib

Reference the work done in issue #2.

### Definition of Done
- Create tests for [`MarketContractOraclize`]() ABI
- Create tests for [`MarketContractFactoryOraclize`](https://github.com/MARKETProtocol/types/issues/7) ABI

### PR DESCRIPTION
**Pull request by arun1595**
##### Description
Tests for MarketContractOraclize and MarketContractFactoryOraclize types

##### Checklist
- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Refers/Fixes
Fixes #8

### CODE REVIEW

**Comment by eswarasai** [comment]
@arun1595 -- You're still awaiting on writing tests for Events correct?

**Comment by arun1595** [comment]
@eswarasai Right, I am still trying to figure out how to write those tests.

**Comment by eswarasai** [comment]
@arun1595 -- Please find my review below :

- We have recently updated the `types` on the `develop` which contains few additional variables 
 -- `COLLATERAL_POOL_FACTORY_ADDRESS`, `COLLATERAL_TOKEN_ADDRESS` which are missing from the tests
- In the recent update, we've modified the types of few variables like `orderHash` to be `string` instead of `BigNumber`. Can you please update the same in your test cases to avoid lint errors?
- #8 also has #7 to be done alongside in the `Definition of Done` section. So can you please write the tests for `MarketContractFactoryOraclize` too?

Let me know once the PR is updated so that I can review and merge it. Thanks :)

**Comment by arun1595** [comment]
@eswarasai I've addressed your comments and squashed my commits into a single one :slightly_smiling_face: 

Let me know if I missed something,

Thanks!

**Pull request merged**
