### PR TITLE
Tests for Events

### PR DESCRIPTION
**Pull request by pfilippi24**
##### Description
WIP PR for event mock tests.
The tests set up the mock event and then assert, that the event is indeed being raised, when the corresponding transaction method is called.

##### Checklist
- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Refers/Fixes
Fixes: #21

### CODE REVIEW

**Comment by eswarasai** [comment]
@pfilippi24 -- This is looking good to me. Would you like to continue adding commits to this PR and merge them all at once or you'd like to create a separate PR for adding tests to the rest of the events?

**Comment by pfilippi24** [comment]
@eswarasai I'll keep adding on to this one.

**Comment by eswarasai** [comment]
@pfilippi24 -- Sounds good 👍 Please do let me know once it's ready for review. Thanks!

**Comment by pfilippi24** [comment]
@eswarasai can you review now

**Pull request merged**
