### PR TITLE
Tests for MarketContract and MarketCollateralPool

### LINKED ISSUE #6: [MarketContract] Test converted TypeScript ABI
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story
As a developer, I need to ensure the MARKET API TypeScript ABIs work correctly so that I can correctly interface with the MARKET contracts.

### Why Is this Needed?
*Summary*: We need to have automated test coverage for all TypeScript ABIs. This started as part of https://github.com/MARKETProtocol/MARKET.js/issues/14. Due to the size and scope of the testing, we created a new project and repo for the MARKET.js types.

### Description
*Type*: Enhancement

### Current Behavior
There is minimal test coverage.

### Expected Behavior
We need 100% test coverage on the TypeScript ABIs.

### Solution
*Summary*:
[Typechain](https://github.com/Neufund/TypeChain) is being used to generate types and the ABIs from which to generate the types is specified as a glob pattern in the package.json under config.typechain.include which is currently set to: Market*|CollateralToken|OraclizeQueryTest|ERC20|OrderLib

Reference the work done in issue #2.

### Definition of Done
- Create tests for the [`MarketContract`]() ABI
- Create tests for the [`MarketCollateralPool `](https://github.com/MARKETProtocol/types/issues/5) ABI

### PR DESCRIPTION
**Pull request by kelvintyb**
##### Description
Add tests for MarketContract and MarketCollateralPool ABIs.

##### Checklist
- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

See https://coveralls.io/builds/17793748 for increased test coverage.
##### Refers/Fixes
Fixes: #5
Fixes #6

### CODE REVIEW

**Comment by pelsasser** [comment]
@kelvintyb - when you have a chance can you please [sign](https://cla-assistant.io/MARKETProtocol/types?pullRequest=24) the CLA.  @eswarasai will review and we can get this merged and paid out ASAP.  Thanks for your contribution!

**Comment by kelvintyb** [comment]
@pelsasser signed 👍

**Comment by eswarasai** [comment]
@kelvintyb -- Is it possible to increase the coverage a bit in order to not reduce the current coverage percentage? Also, `MarketContract.ts` has some formatting changes. Is it done by the IDE or style linter?

**Comment by kelvintyb** [comment]
Added more tests to MarketContractOraclize as I wasn't sure how to test the Event functions. Coverage has been increased past the previous threshold (https://coveralls.io/builds/17793748). 

Also rolled back MarketContract.ts changes, they were done by my IDE's autoformatter.

**Pull request merged**
